version: "3.6"

services:
  database:
    image: postgres:13.0-alpine
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amcef
    volumes:
      - amcef-database:/var/lib/postgresql/data


  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  amcef-database:
